#!/bin/sh -ex
filename=$1
if [ -z "$filename" ] ; then
    echo missing argument
    exit 1
fi
openssl enc -aes-256-cbc -pbkdf2 -salt -in ${filename} -out ${filename}.enc
chmod 600 ${filename}.enc
shred -u ${filename}
