#!/usr/bin/env perl
use strict;
use warnings;
use Time::HiRes qw( usleep time );
my $delay = ( $ARGV[0] || 10 ) * 1000;
my $line  = $ARGV[1] || 'y';
my $start = time;
my $span  = undef;
while (1) {
    syswrite STDOUT, "$line\n";
    $span = $delay - ( time - $start ) * 1000000;
    usleep($span) if ( $span > 0 );
    $start = time;
}
