#!/bin/sh -x

cd $HOME/Documents/Config/pop-os    
sudo cp -rv etc /
sudo chmod -R go-rwx /etc/luks-keys
sudo chmod 600 /etc/NetworkManager/system-connections/*

sudo systemctl restart NetworkManager

sudo apt update && sudo apt dist-upgrade -y
sudo apt install -y vim \
                    gstreamer1.0-libav \
                    lutris \
                    steam \
                    gamemode \
                    neofetch \

flatpak install -y com.discordapp.Discord                                 
flatpak install -y com.mattermost.Desktop                                 
flatpak install -y com.slack.Slack                                        
flatpak install -y io.atom.Atom                                           
flatpak install -y org.gimp.GIMP                                          
flatpak install -y org.gnome.Evolution                                    
flatpak install -y org.gnome.Rhythmbox3                                   
flatpak install -y org.signal.Signal                                      
flatpak install -y us.zoom.Zoom                                           

sudo apt purge -y geary
sudo apt autoremove -y --purge
